import type {
  EventRow,
  TeamMemberRow,
  HighlightRow,
  BlogPostRow,
  PartnerRow,
  GalleryImageRow,
} from "./database.types";

export const MOCK_EVENTS: EventRow[] = [
  {
    id: "1",
    slug: "vibe-code-2025",
    title: "VIBE CODE Hackathon",
    description: "A 12-hour AI-focused hackathon where students ideate, build, and refine AI-driven applications through hands-on collaboration and real-world problem solving. Held at Draper Startup House.",
    long_description: null,
    event_date: "2025-11-09",
    event_time: "9:00 AM",
    location: "Draper Startup House, Hyderabad",
    category: "Hackathon",
    mode: "OFFLINE",
    speakers: "Industry Mentors & Judges",
    attendees: 200,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/vibe-code-hackathon.jpg",
    winners: ["Dhanvantari Team", "HackstreetBoys", "Ravens"],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 10,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "2",
    slug: "ai-agents-workshop",
    title: "AI Agents Workshop",
    description: "Hands-on experience in AI and automation. Participants learned to build and deploy AI workflows using n8n, and explored tools like Cursor, Lovable, and Napkin AI.",
    long_description: null,
    event_date: "2025-08-07",
    event_time: "10:00 AM",
    location: "SNIST Campus, Hyderabad",
    category: "Workshop",
    mode: "OFFLINE",
    speakers: "Chandan Kumar Cheripally, Shubham Lal, Chandrashekhar M",
    attendees: 120,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/ai-agents.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 20,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "3",
    slug: "summer-backend-2025",
    title: "Summer Backend Bootcamp",
    description: "Practical bootcamp on server-side development covering client-server architecture, RESTful APIs, MongoDB/MySQL, Node.js and Express.js with live coding and mini-projects.",
    long_description: null,
    event_date: "2025-05-20",
    event_time: "10:00 AM",
    location: "SNIST Campus, Hyderabad",
    category: "Bootcamp",
    mode: "OFFLINE",
    speakers: "SDC Core Team",
    attendees: 80,
    seats: null,
    duration: "2 Weeks",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/backend-bootcamp.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 30,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "4",
    slug: "ai-summit-2025",
    title: "AI Summit 2025",
    description: "Hands-on sessions on building LLMs, AI agents, and custom GPTs. Featured book launch of Azure OpenAI Essentials, VR experience, and panel discussions on AI's impact on industries.",
    long_description: null,
    event_date: "2025-03-15",
    event_time: "9:00 AM",
    location: "Swecha Open Source, Hyderabad",
    category: "Conference",
    mode: "OFFLINE",
    speakers: "Adithya Saladi, Dodagatta Nihar, Tech Boy Deepak",
    attendees: 300,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/ai-summit.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 40,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "5",
    slug: "ai-day-2025",
    title: "AI Day 2025",
    description: "Focused on equipping students with AI knowledge and skills. Session by Om Ashish Mishra on How AI Works. First in a series of AI-focused events by SDC INDIA.",
    long_description: null,
    event_date: "2025-02-16",
    event_time: "10:00 AM",
    location: "Growth Hub, Hyderabad",
    category: "Workshop",
    mode: "OFFLINE",
    speakers: "Om Ashish Mishra, Tech Boy Deepak",
    attendees: 100,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/ai-day-2025.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 50,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "6",
    slug: "hash-it-out-2",
    title: "Hash-It-Out Season 2",
    description: "State-level hackathon bringing together students from across Telangana to solve real-world problems. Focused on team building, networking, and technical innovation.",
    long_description: null,
    event_date: "2024-11-20",
    event_time: "9:00 AM",
    location: "SNIST Campus, Hyderabad",
    category: "Hackathon",
    mode: "OFFLINE",
    speakers: "Industry Mentors",
    attendees: 400,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/hash-it-out-2.jpg",
    winners: ["Sticky Fingers", "Team Spartans", "Team Vrinchi"],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 60,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "7",
    slug: "uxplosion-2",
    title: "UXplosion 2.0",
    description: "Five-day intensive UI/UX bootcamp led by Madhu Pilli covering design thinking, wireframing, prototyping, Figma advanced techniques, and concluding with a live hackathon.",
    long_description: null,
    event_date: "2024-09-15",
    event_time: "7:00 PM",
    location: "SNIST Campus, Hyderabad",
    category: "Workshop",
    mode: "OFFLINE",
    speakers: "Madhu Pilli",
    attendees: 150,
    seats: null,
    duration: "6 Days",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/uxplosion-1.jpg",
    winners: ["Team MAC 1", "Team VisionX", "Team 2 Pixels Apart"],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 70,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "8",
    slug: "uxplosion-1",
    title: "UXplosion – Where Creativity Meets Functionality",
    description: "Seven-day UI/UX bootcamp with Frederick Devarampati (Forbes 30U30 Asia). Covered Figma, prototyping, component creation, and concluded with India's first UI/UX designing hackathon.",
    long_description: null,
    event_date: "2024-06-17",
    event_time: "7:00 PM",
    location: "Online + SNIST Campus",
    category: "Workshop",
    mode: "HYBRID",
    speakers: "Frederick Devarampati – Founder, CEO Hotnot Fashion",
    attendees: 180,
    seats: null,
    duration: "7 Days",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/uxplosion-1.jpg",
    winners: ["Team Design Squat", "Team Anonymous", "Team High Flyers"],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 80,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "9",
    slug: "beyond-tech-2024",
    title: "Beyond Tech 2024 Hyderabad",
    description: "5+ speakers across 5 technology topics with 9+ hours of keynotes and hands-on learning. 250+ participants at Microsoft Hyderabad Campus.",
    long_description: null,
    event_date: "2024-06-15",
    event_time: "9:00 AM",
    location: "Microsoft Hyderabad Campus",
    category: "Conference",
    mode: "OFFLINE",
    speakers: "Harshith Sai Tunuguntla, Adithya Saladi, Saideep Reddy",
    attendees: 250,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/beyond-tech-2024.png",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 90,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "10",
    slug: "tech-vision-bangalore",
    title: "Tech Vision – Bangalore",
    description: "Hosted at Microsoft Bangalore with sessions on Prompt Engineering, UI/UX, Data Engineering, AI, Reverse Engineering, and Open AI from renowned industry speakers.",
    long_description: null,
    event_date: "2024-03-20",
    event_time: "9:00 AM",
    location: "Microsoft Bangalore",
    category: "Conference",
    mode: "OFFLINE",
    speakers: "Harshith Sai Tunuguntla, Anurag Srivastava, Lakshit Pant",
    attendees: 150,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/techvision.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 100,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "11",
    slug: "aleph-zero-blockchain",
    title: "Aleph Zero Blockchain Workshop",
    description: "Deep dive into Blockchain & Web3 with hands-on quests, NFT rewards, and networking. Covered Blockchain fundamentals, Web3, and the Aleph Zero ecosystem.",
    long_description: null,
    event_date: "2024-02-15",
    event_time: "2:00 PM",
    location: "SNIST Campus, Hyderabad",
    category: "Workshop",
    mode: "OFFLINE",
    speakers: "Rajashekar Makala, Siv Ram Shastri Jonnalagadda",
    attendees: 100,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/blockchain.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 110,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "12",
    slug: "ds-ai-workshop-2023",
    title: "Data Science & AI Workshop",
    description: "Collaboration with Microsoft Learn Student Ambassadors at Microsoft Office. 240+ students learned data science fundamentals, ML, and predictive modeling.",
    long_description: null,
    event_date: "2023-11-10",
    event_time: "10:00 AM",
    location: "Microsoft Office, Hyderabad",
    category: "Workshop",
    mode: "OFFLINE",
    speakers: "Bilal Aamer, Moinuddin Mohammed",
    attendees: 240,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/ds-workshop.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 120,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "13",
    slug: "hash-it-out-1",
    title: "Hash-It-Out Season 1",
    description: "SDC's inaugural state-level hackathon on October 6th. Brought together students to solve local problems using technology. Teams from CMRCET, SIET, and SNIST competed.",
    long_description: null,
    event_date: "2023-10-06",
    event_time: "9:00 AM",
    location: "SNIST Campus, Hyderabad",
    category: "Hackathon",
    mode: "OFFLINE",
    speakers: "Industry Mentors",
    attendees: 200,
    seats: null,
    duration: "1 Day",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/hackathon_event.png",
    winners: ["Tech Innovators (CMRCET)", "The Originals (SIET)", "Team Ashish (SNIST)"],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 130,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "14",
    slug: "summer-tech-camp-2023",
    title: "SDC Summer Tech Camp",
    description: "30-day summer bootcamp for beginners covering HTML, CSS, JavaScript, and Bootstrap frontend development. Held on alternative days from May 16 to June 10, 2023.",
    long_description: null,
    event_date: "2023-05-16",
    event_time: "10:00 AM",
    location: "Online",
    category: "Bootcamp",
    mode: "ONLINE",
    speakers: "SDC Core Team",
    attendees: 100,
    seats: null,
    duration: "30 Days",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/tech-bootcamp.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 140,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "15",
    slug: "hack-for-hyderabad-1",
    title: "HACK HYDERABAD EDITION-1",
    description: "A National Level Hackathon that brings together developers nationwide to collaborate, innovate, and build impactful solutions addressing real-world challenges through technology.",
    long_description: null,
    event_date: null,
    event_time: null,
    location: "Hyderabad",
    category: "Hackathon",
    mode: "OFFLINE",
    speakers: "TBD",
    attendees: 0,
    seats: 300,
    duration: "12 Hours",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/hackwithhyd.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 1,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "16",
    slug: "hack-for-hyderabad-2",
    title: "HACK HYDERABAD EDITION-2",
    description: "A National Level Hackathon that brings together developers nationwide to collaborate, innovate, and build impactful solutions addressing real-world challenges through technology.",
    long_description: null,
    event_date: null,
    event_time: null,
    location: "Hyderabad",
    category: "Hackathon",
    mode: "OFFLINE",
    speakers: "TBD",
    attendees: 0,
    seats: 300,
    duration: "12 Hours",
    registration_url: "#",
    registration_open: false,
    image_url: "/assets/events/hackwithhyd.jpg",
    winners: [],
    tags: [],
    agenda: null,
    what_you_will_learn: [],
    who_should_attend: [],
    is_published: true,
    display_order: 2,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
];

export const MOCK_TEAM_MEMBERS: TeamMemberRow[] = [
  {
    id: "1",
    slug: "chandrashekhar-m",
    initials: "CM",
    name: "Chandrashekhar M",
    role: "Founder",
    bio: "Founded SDC in 2022 at Sreenidhi Institute of Science and Technology (SNIST). A SNIST alumnus from the 2021–2024 batch, his vision was to create a space where students could grow technically through collaboration and hands-on learning — moving beyond classroom theory into real-world technology. Under his leadership, SDC has grown to 5000+ members with a national footprint as SDC INDIA.",
    skills: ["Community Building", "Vision", "Mentorship", "Leadership", "Event Strategy"],
    impact: "Founded SDC · Grew it to 5000+ members",
    gradient: "linear-gradient(135deg,#e84393,#f97316)",
    section: "Founder",
    photo_url: null,
    github_url: null,
    linkedin_url: null,
    twitter_url: null,
    email: null,
    is_published: true,
    display_order: 1,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "2",
    slug: "pavan-kumar",
    initials: "PK",
    name: "Pavan Kumar",
    role: "Core Contributor",
    bio: "Active contributor to SDC INDIA's open-source projects and community platforms. Works on the SDC website and developer tooling.",
    skills: ["Web Development", "TypeScript", "React", "Open Source"],
    impact: "SDC INDIA website & tooling",
    gradient: "linear-gradient(135deg,#22c55e,#06b6d4)",
    section: "Core",
    photo_url: null,
    github_url: "https://github.com/goutipavankumar1249",
    linkedin_url: null,
    twitter_url: null,
    email: null,
    is_published: true,
    display_order: 10,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "3",
    slug: "rithwik",
    initials: "RT",
    name: "Rithwik",
    role: "Core Contributor",
    bio: "Active contributor to SDC INDIA's GitHub repositories. Part of the team driving open-source initiatives within the community.",
    skills: ["Development", "Open Source", "Collaboration"],
    impact: "Open-source contributions",
    gradient: "linear-gradient(135deg,#c2185b,#e84393)",
    section: "Core",
    photo_url: null,
    github_url: "https://github.com/Rithwik29102006",
    linkedin_url: null,
    twitter_url: null,
    email: null,
    is_published: true,
    display_order: 11,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "4",
    slug: "bhavitha",
    initials: "BH",
    name: "Bhavitha",
    role: "Core Contributor",
    bio: "Contributor to SDC INDIA's projects, focused on building and maintaining community-driven open-source work.",
    skills: ["Development", "Open Source", "Collaboration"],
    impact: "Project contributions",
    gradient: "linear-gradient(135deg,#f97316,#c2185b)",
    section: "Core",
    photo_url: null,
    github_url: "https://github.com/bhavitha-1306",
    linkedin_url: null,
    twitter_url: null,
    email: null,
    is_published: true,
    display_order: 12,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "5",
    slug: "shashank-puram",
    initials: "SP",
    name: "Shashank Puram",
    role: "Core Contributor",
    bio: "Contributor to SDC INDIA's open-source repositories and engineering initiatives.",
    skills: ["Development", "Open Source", "Engineering"],
    impact: "Engineering contributions",
    gradient: "linear-gradient(135deg,#06b6d4,#f59e0b)",
    section: "Core",
    photo_url: null,
    github_url: "https://github.com/ShashankPuram",
    linkedin_url: null,
    twitter_url: null,
    email: null,
    is_published: true,
    display_order: 13,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
];

export const MOCK_HIGHLIGHTS: HighlightRow[] = [
  {
    id: "1",
    slug: "dhanvantari",
    team_name: "Dhanvantari Team",
    initials: "DT",
    position: "1st",
    position_icon: "🏆",
    event_id: "1",
    event_name: "VIBE CODE Hackathon",
    event_date_label: "November 2025",
    event_image_url: "/assets/events/vibe-code-hackathon.jpg",
    description: "Crowned champions of VIBE CODE 2025 — a 12-hour AI-focused hackathon at Draper Startup House. Their winning entry showcased rapid ideation, technical depth, and a real-world problem solved through AI-driven engineering.",
    gradient: "linear-gradient(135deg,#e84393,#f97316)",
    stats: [
      { value: "1st", label: "PLACE" },
      { value: "12h", label: "BUILD TIME" },
      { value: "200", label: "COMPETITORS" },
      { value: "AI", label: "FOCUS" },
    ],
    is_published: true,
    display_order: 1,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "2",
    slug: "hackstreet",
    team_name: "HackstreetBoys",
    initials: "HB",
    position: "2nd",
    position_icon: "🥈",
    event_id: "1",
    event_name: "VIBE CODE Hackathon",
    event_date_label: "November 2025",
    event_image_url: "/assets/events/vibe-code-hackathon.jpg",
    description: "Strong runners-up at VIBE CODE Hackathon 2025. Shipped an AI-driven product in 12 hours alongside 200 fellow developers — demonstrating sharp engineering and team coordination under time pressure.",
    gradient: "linear-gradient(135deg,#c2185b,#e84393)",
    stats: [
      { value: "2nd", label: "PLACE" },
      { value: "12h", label: "BUILD TIME" },
      { value: "200", label: "COMPETITORS" },
      { value: "AI", label: "FOCUS" },
    ],
    is_published: true,
    display_order: 2,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "3",
    slug: "sticky",
    team_name: "Sticky Fingers",
    initials: "SF",
    position: "1st",
    position_icon: "🏆",
    event_id: "6",
    event_name: "Hash-It-Out Season 2",
    event_date_label: "November 2024",
    event_image_url: "/assets/events/hash-it-out-2.jpg",
    description: "Winners of Hash-It-Out Season 2 — SDC's Telangana state-level hackathon with 400 students. Solved a real-world problem with elegant code, clean architecture, and standout teamwork.",
    gradient: "linear-gradient(135deg,#22c55e,#06b6d4)",
    stats: [
      { value: "1st", label: "PLACE" },
      { value: "400", label: "COMPETITORS" },
      { value: "STATE", label: "LEVEL" },
      { value: "1", label: "DAY" },
    ],
    is_published: true,
    display_order: 3,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "4",
    slug: "mac1",
    team_name: "Team MAC 1",
    initials: "M1",
    position: "1st",
    position_icon: "🏆",
    event_id: "7",
    event_name: "UXplosion 2.0",
    event_date_label: "September 2024",
    event_image_url: "/assets/events/uxplosion-1.jpg",
    description: "Winners of UXplosion 2.0 — the five-day UI/UX bootcamp led by Madhu Pilli, culminating in a live design hackathon. Beautiful interface work, sharp execution, and a clear user-centered story.",
    gradient: "linear-gradient(135deg,#f97316,#c2185b)",
    stats: [
      { value: "1st", label: "PLACE" },
      { value: "150", label: "COMPETITORS" },
      { value: "6", label: "DAYS" },
      { value: "Figma", label: "TOOL" },
    ],
    is_published: true,
    display_order: 4,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "5",
    slug: "designsquat",
    team_name: "Team Design Squat",
    initials: "DS",
    position: "1st",
    position_icon: "🏆",
    event_id: "8",
    event_name: "UXplosion Season 1",
    event_date_label: "June 2024",
    event_image_url: "/assets/events/uxplosion-2.jpg",
    description: "Winners of UXplosion Season 1 — India's first UI/UX designing hackathon, mentored by Forbes 30U30 Asia honoree Frederick Devarampati. Strong concept, polished execution, deserved win.",
    gradient: "linear-gradient(135deg,#06b6d4,#c2185b)",
    stats: [
      { value: "1st", label: "PLACE" },
      { value: "180", label: "COMPETITORS" },
      { value: "7", label: "DAYS" },
      { value: "1st", label: "IN INDIA" },
    ],
    is_published: true,
    display_order: 5,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "6",
    slug: "techinnovators",
    team_name: "Tech Innovators (CMRCET)",
    initials: "TI",
    position: "1st",
    position_icon: "🏆",
    event_id: "13",
    event_name: "Hash-It-Out Season 1",
    event_date_label: "October 2023",
    event_image_url: "/assets/events/hackathon_event.png",
    description: "Winners of Hash-It-Out Season 1 — SDC's inaugural hackathon. The CMRCET team beat squads from SIET and SNIST with a sharp local-problem solution that earned them the top prize.",
    gradient: "linear-gradient(135deg,#f59e0b,#e84393)",
    stats: [
      { value: "1st", label: "PLACE" },
      { value: "200", label: "COMPETITORS" },
      { value: "3", label: "COLLEGES" },
      { value: "1st", label: "EDITION" },
    ],
    is_published: true,
    display_order: 6,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
];

export const MOCK_BLOG_POSTS: BlogPostRow[] = [
  {
    id: "post-1",
    slug: "story-behind-sdc",
    title: "The Story Behind SDC: A Community Built for Builders",
    category: "article",
    publish_date: "2026-03-01",
    read_time: "5 min read",
    cover_image_url: "/assets/blog/sdc-india-logo.jpeg",
    excerpt: "The Student Developers Community (SDC) was established in 2022 at Sreenidhi Institute of Science and Technology. The goal was simple: create an environment where students can learn by building.",
    content_blocks: [
      {
        paragraphs: [
          "The Student Developers Community (SDC) was established in 2022 at Sreenidhi Institute of Science and Technology (SNIST) with a clear mission: build a student-first technical ecosystem.",
          "From day one, SDC focused on practical exposure through workshops, bootcamps, hackathons, and peer collaboration.",
        ],
        quote: "Learning by doing - that's the SDC way.",
      },
      {
        title: "Where We Are Today",
        paragraphs: [
          "Today, SDC has grown into a strong technical community with over 5000+ members and a growing national footprint under SDC INDIA.",
        ],
      },
      {
        title: "Our Core Values",
        bullets: [
          "Open and inclusive learning environment",
          "Real-world, hands-on exposure",
          "Peer collaboration over competition",
          "Industry-aligned skill building",
        ],
      },
    ],
    is_published: true,
    display_order: 1,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "post-2",
    slug: "founder-and-vision",
    title: "Founder and Vision Behind SDC",
    category: "community",
    publish_date: "2026-02-01",
    read_time: "4 min read",
    cover_image_url: "/assets/blog/community-1.jpeg",
    excerpt: "Founded by Chandrashekhar M, SDC was built to close the gap between classroom learning and industry expectations.",
    content_blocks: [
      {
        paragraphs: [
          "SDC was founded by Mr. Chandrashekhar M, a SNIST alumnus from the 2021-2024 batch.",
          "His vision centered on creating an inclusive environment where students can gain confidence through collaboration and practical experience.",
        ],
      },
      {
        title: "Growth Under Leadership",
        bullets: [
          "Hosted impactful student-focused events",
          "Built collaborations with industry professionals",
          "Formed partnerships with national communities",
          "Expanded to 5000+ members",
        ],
        quote: "The founding values continue to shape SDC's culture and growth path.",
      },
    ],
    is_published: true,
    display_order: 2,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "post-3",
    slug: "major-events-and-hackathons",
    title: "Major Events and Hackathons That Defined SDC",
    category: "event",
    publish_date: "2025-12-01",
    read_time: "6 min read",
    cover_image_url: "/assets/blog/event.jpeg",
    excerpt: "SDC events evolved into practical career launchpads through workshops, hackathons, and national partnerships.",
    content_blocks: [
      {
        title: "Key Initiatives",
        bullets: [
          "SDC Summer Tech Camp",
          "UI/UX Workshop",
          "Python for Data Science",
          "Backend Development Bootcamp",
          "AI Workshop at Microsoft",
          "Beyond Tech at Microsoft Hyderabad",
          "AI Day at Growth Hub",
          "AI Summit 2025",
          "Aleph Zero Blockchain Workshop",
          "Smart India Hackathon Guidance Sessions",
        ],
      },
      {
        title: "Flagship Hackathons",
        paragraphs: [
          "Hash It Out and UX-Plosion became defining experiences where students built deployable solutions with mentorship from industry experts.",
        ],
      },
      {
        title: "Community Partnerships",
        paragraphs: [
          "SDC partnered with events like PyCon India, Hack This Fall, Hack 4 Hire, Social Media Summit, Techknowthon, and GDSC WOW.",
        ],
      },
    ],
    is_published: true,
    display_order: 3,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "post-4",
    slug: "campus-to-sdc-india",
    title: "From Campus Club to SDC INDIA",
    category: "growth",
    publish_date: "2025-10-01",
    read_time: "3 min read",
    cover_image_url: "/assets/blog/snist.jpeg",
    excerpt: "SDC expanded from a campus initiative into a nationwide student developer movement with new chapters and broader impact.",
    content_blocks: [
      {
        paragraphs: [
          "SDC scaled from a local campus initiative into SDC INDIA, expanding across institutions and regions.",
          "The launch of chapters like SDC SPEC strengthened the innovation ecosystem and reach.",
        ],
        quote: "The long-term vision is a connected nationwide student developer network.",
      },
    ],
    is_published: true,
    display_order: 4,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "post-5",
    slug: "digital-presence",
    title: "SDC's Digital Presence: Where the Community Lives Online",
    category: "digital",
    publish_date: "2025-08-01",
    read_time: "3 min read",
    cover_image_url: "/assets/blog/community-3.jpeg",
    excerpt: "From the website to GitHub, LinkedIn, and Instagram, SDC's digital channels keep the community connected.",
    content_blocks: [
      {
        paragraphs: [
          "The SDC India website serves as the central hub for mission updates, events, and community initiatives.",
        ],
      },
      {
        title: "Primary Platforms",
        bullets: [
          "LinkedIn for professional updates and opportunities",
          "Instagram for highlights and community storytelling",
          "GitHub for open-source collaboration and project sharing",
        ],
      },
    ],
    is_published: true,
    display_order: 5,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "post-6",
    slug: "why-sdc-member",
    title: "Why Being an SDC Member Changes Everything",
    category: "article",
    publish_date: "2025-06-01",
    read_time: "5 min read",
    cover_image_url: "/assets/blog/community-2.jpeg",
    excerpt: "Membership unlocks mentorship, practical exposure, events, and a high-trust community that accelerates growth.",
    content_blocks: [
      {
        title: "Experiential Learning and Mentorship",
        paragraphs: [
          "Through events like HASH IT OUT and UX-Plosion, students solve real-world problems with mentorship and structured feedback.",
        ],
      },
      {
        title: "Professional Networking",
        paragraphs: [
          "National partnerships and industry-hosted events help members connect with recruiters, founders, and practitioners.",
        ],
      },
      {
        title: "Holistic Growth",
        bullets: [
          "Teamwork and leadership",
          "Communication and presentation",
          "Open-source contribution",
          "Public project showcases",
        ],
      },
    ],
    is_published: true,
    display_order: 6,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "post-7",
    slug: "beyond-tech-microsoft",
    title: "Beyond Tech at Microsoft Hyderabad: A Recap",
    category: "event",
    publish_date: "2025-04-01",
    read_time: "4 min read",
    cover_image_url: "/assets/blog/community-3.jpeg",
    excerpt: "Beyond Tech brought students, professionals, and founders together to discuss practical career pathways and AI innovation.",
    content_blocks: [
      {
        paragraphs: [
          "SDC co-hosted Beyond Tech and AI workshop sessions at Microsoft Hyderabad to connect students directly with experienced professionals.",
        ],
      },
      {
        title: "Key Takeaways",
        bullets: [
          "Networking with recruiters and startup founders",
          "Live Q and A with industry experts",
          "AI workshops around product use cases",
          "Exposure to enterprise innovation workflows",
        ],
      },
    ],
    is_published: true,
    display_order: 7,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
];

export const MOCK_PARTNERS: PartnerRow[] = [
  {
    id: "1",
    slug: "microsoft-learn",
    name: "Microsoft Learn",
    logo_url: "/assets/partners/microsoft-learn.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 1,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "2",
    slug: "iete",
    name: "IETE",
    logo_url: "/assets/partners/iete.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 2,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "3",
    slug: "code-sprint",
    name: "Code Sprint",
    logo_url: "/assets/partners/code-sprint.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 3,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "4",
    slug: "hack-this-fall",
    name: "Hack This Fall",
    logo_url: "/assets/partners/hack-this-fall.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 4,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "5",
    slug: "gdsc-wow",
    name: "Google Developer Student Clubs WOW",
    logo_url: "/assets/partners/gdsc-wow.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 5,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "6",
    slug: "edventure",
    name: "EdVenture Park",
    logo_url: "/assets/partners/edventure.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 6,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "7",
    slug: "pycon-india",
    name: "PyCon India Hyderabad 2023",
    logo_url: "/assets/partners/pycon.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 7,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "8",
    slug: "st",
    name: "ST",
    logo_url: "/assets/partners/st.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 8,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "9",
    slug: "talentmapp",
    name: "Talentmapp",
    logo_url: "/assets/partners/talentmapp.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 9,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "10",
    slug: "ecell",
    name: "E-Cell",
    logo_url: "/assets/partners/ecell.svg",
    website_url: null,
    description: null,
    tier: "standard",
    is_published: true,
    display_order: 10,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
];

export const MOCK_GALLERY_IMAGES: GalleryImageRow[] = [
  {
    id: "g1",
    slug: null,
    image_url: "/assets/blog/event.jpeg",
    alt_text: "SDC Event",
    caption: null,
    span_classes: "col-span-2 aspect-[2/1]",
    event_id: null,
    is_published: true,
    display_order: 1,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "g2",
    slug: null,
    image_url: "/assets/blog/snist.jpeg",
    alt_text: "SNIST Campus",
    caption: null,
    span_classes: "aspect-square",
    event_id: null,
    is_published: true,
    display_order: 2,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "g3",
    slug: null,
    image_url: "/assets/blog/community-1.jpeg",
    alt_text: "Community",
    caption: null,
    span_classes: "aspect-square",
    event_id: null,
    is_published: true,
    display_order: 3,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "g4",
    slug: null,
    image_url: "/assets/blog/community-2.jpeg",
    alt_text: "Members",
    caption: null,
    span_classes: "aspect-square",
    event_id: null,
    is_published: true,
    display_order: 4,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
  {
    id: "g5",
    slug: null,
    image_url: "/assets/blog/community-3.jpeg",
    alt_text: "Team",
    caption: null,
    span_classes: "aspect-square",
    event_id: null,
    is_published: true,
    display_order: 5,
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    created_by: null,
    updated_by: null,
    deleted_at: null,
  },
];
